### ISSUE TITLE
Make QR code on the certificates leading to the link that explains all certificates

### ISSUE THREAD

**Issue by jefcorral** [sirking1991/fcoa-members#159]
# Why
We need a way to verify that the certificate is authentic.

# Solution
- Add a QR code to the Certificate PDF. The content of the QR code should be as follows:
`https://fcoa.online/verify-certificate/{CERTIFICATE_NUMBER}`
- Add the route for `/verify-certificate`, and display the following info: Certificate #, Issue Date & Location, Certified By, Issued to (member name) and the Course

**Comment by Jelout** [comment]
checked

**Comment by Jelout** [comment]
checked
