### ISSUE TITLE
Allow Admin to impersonate user

### ISSUE THREAD

**Issue by sirking1991** [sirking1991/fcoa-members#169]
# Why
In able for us to validate and replicate the issues our members are experiencing, we need to be able to login to their account without asking for their password.

# Solution
As an Admin user, in the members list, there should be a "Login as this user" button on each member tab. When I click it, it should refresh the page and I should be login as that user.

# Tech notes
Use `Auth::login` (see https://laracasts.com/discuss/channels/general-discussion/impersonating-users)

**Comment by Jelout** [comment]
checked
