### ISSUE TITLE
HIGH PRIORITY : Signing up is currently not available, it gives an Error 500

### ISSUE THREAD

**Issue by Jelout** [sirking1991/fcoa-members#222]

**Comment by jefcorral** [comment]
sir @sirking1991 need to add this in servers env
RECAPTCHA_SECRET=6LeENa8pAAAAAMObjttdksCAFDblTpsHyeDMI00d
RECAPTCHA_SITEKEY=6LeENa8pAAAAAHFQ8H0NBzjX1vKT6AdCN4VJavyw

and run php artisan config:clear

**Comment by Jelout** [comment]
fixed
